import json
import os
from django import template
from django.conf import settings
from django.templatetags.static import static

register = template.Library()

# Load Vite manifest only once
def load_manifest():
    manifest_path = os.path.join(settings.BASE_DIR, "static", "frontend", ".vite", "manifest.json")
    with open(manifest_path, "r") as f:
        return json.load(f)

MANIFEST = load_manifest()


@register.simple_tag
def vite_asset(asset_name):
    """
    Returns the correct hashed asset path from manifest.json
    """
    try:
        hashed_name = MANIFEST[asset_name]["file"]
        return static(f"frontend/{hashed_name}")
    except KeyError:
        return ""


@register.simple_tag
def vite_css(asset_name):
    """
    Loads any css generated by the script entry
    """
    tags = ""
    try:
        css_files = MANIFEST[asset_name].get("css", [])
        for css in css_files:
            tags += f'<link rel="stylesheet" href="{static("frontend/" + css)}">\n'
    except KeyError:
        pass
    return tags
