# Generated by Django 5.2.1 on 2025-07-18 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_paymentmethod_user_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registration_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_postal_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_street_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='marketing_optin',
            field=models.BooleanField(default=False, help_text='User has opted-in to receive marketing communications', verbose_name='marketing opt-in'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in international format: '+999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]
