# Generated by Django 5.2.4 on 2025-10-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_last_login_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marketing_optin',
            field=models.BooleanField(default=False, verbose_name='marketing opt-in'),
        ),
    ]
