# Generated by Django 5.2.4 on 2025-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marketing_optin',
            field=models.BooleanField(default=False, help_text='User has opted-in to receive marketing communications', verbose_name='marketing opt-in'),
        ),
    ]
