# Generated by Django 5.2.4 on 2025-10-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('shipping', 'Shipping'), ('billing', 'Billing'), ('other', 'Other')], default='shipping', max_length=20, verbose_name='address type'),
        ),
    ]
