# Generated by Django 5.2.4 on 2025-07-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('address_add', 'Address Added'), ('payment_add', 'Payment Method Added'), ('consent_update', 'Consent Updated')], max_length=50),
        ),
    ]
