# Generated by Django 5.2.4 on 2025-07-27 09:31
from django.conf import settings
from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model('users', 'Profile')

    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]