# Generated by Django 5.2.4 on 2025-10-26 12:24

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2),
        ),
    ]
