# Generated by Django 5.2.4 on 2025-07-27 09:54
from django.db import migrations
from django.conf import settings



def remove_duplicate_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model('users', 'Profile')

    for user in User.objects.all():
        profiles = Profile.objects.filter(user=user)
        if profiles.count() > 1:
            # Keep the first profile and delete duplicates
            primary = profiles.first()
            profiles.exclude(pk=primary.pk).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_auto_20250727_1231'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_profiles),
    ]