# Generated by Django 5.2.4 on 2025-10-29 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Update'), ('address_add', 'Address Added'), ('payment_add', 'Payment Method Added'), ('consent_update', 'Consent Updated')], max_length=50),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=128, unique=True, verbose_name='token hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(default=None, verbose_name='expires at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'password reset token',
                'verbose_name_plural': 'password reset tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
