# Generated by Django 5.2.4 on 2025-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_activitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en-us', max_length=10, verbose_name='preferred language'),
        ),
    ]
