# Generated by Django 5.2.1 on 2025-06-17 07:08

from django.db import migrations
from django.template.defaultfilters import slugify

from store.constants import CATEGORIES


def create_categories(apps, schema_editor):
    Category = apps.get_model('store', 'Category')

    for parent_name, children_names in CATEGORIES.items():
        parent = Category.objects.create(
            name=parent_name,
            slug=slugify(parent_name),
            is_active=True
        )

        for child_name in children_names:
            Category.objects.create(
                name=child_name,
                slug=slugify(child_name),
                parent=parent,
                is_active=True
            )


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]