# Generated by Django 5.2.1 on 2025-06-17 07:25

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20250617_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='categories/default.png', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['email'], name='store_newsl_email_d13a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['confirmed'], name='store_newsl_confirm_6070ac_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['unsubscribed'], name='store_newsl_unsubsc_44a577_idx'),
        ),
    ]
