# Generated by Django 5.2.4 on 2025-10-20

from django.db import migrations, models
import django.db.models.deletion

def clean_supplier_ids(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    # Convert empty string suppliers to NULL before FK migration
    Product.objects.filter(supplier="").update(supplier=None)

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_enable_pg_trgm'),
    ]

    operations = [
        # Step 1: Create lookup tables
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),

        # Step 2: Add search fields (safe)
        migrations.AddField(
            model_name='product',
            name='search_brand',
            field=models.CharField(max_length=150, blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_supplier',
            field=models.CharField(max_length=150, blank=True),
        ),

        # Step 3: TEMP make supplier nullable BEFORE FK conversion
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),

        # Step 4: Clean bad data
        migrations.RunPython(clean_supplier_ids, migrations.RunPython.noop),

        # Step 5: NOW convert supplier to FK safely
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(
                to='store.supplier',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products'
            ),
        ),

        # Step 6: Add brand FK
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(
                to='store.brand',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products'
            ),
        ),
    ]
