# Generated by Django 5.2.1 on 2025-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productimage_color_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='is_dropship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_time',
            field=models.CharField(default='10-20 days', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['color'], name='store_produ_color_3f9b58_idx'),
        ),
    ]
