# Generated by Django 5.2.1 on 2025-06-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_lft_category_mptt_level_category_rght_and_more'),
    ]

    operations = [
    ]
