# Generated by Django 5.2.1 on 2025-06-29 20:30
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_search_vector_product_product_search_idx_and_more'),
    ]


    operations = [
        TrigramExtension(),  # Installs pg_trgm
    ]
