# Generated by Django 5.2.4 on 2025-10-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_supplier_name_alter_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
