# Generated by Django 5.2.4 on 2025-10-27 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review_helpful_count_stocknotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_voters',
            field=models.ManyToManyField(blank=True, related_name='helpful_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
