# Generated by Django 5.2.4 on 2025-10-29 06:22

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_review_helpful_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], default='KES', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], default='KES', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], default='KES', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=djmoney.models.fields.MoneyField(blank=True, db_index=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14),
        ),
    ]
