# Generated by Django 5.2.1 on 2025-07-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_tags'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_id_2abda1_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_search__16796e_gin',
            old_name='product_search_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_name_5e57da_idx',
            old_name='product_name_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'),
        ),
    ]
