# Generated by Django 5.2.4 on 2025-11-07 12:32

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_discount_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False, help_text='Check if this product qualifies for free shipping'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), help_text='Shipping cost for this product (leave blank for free shipping)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], default='KES', editable=False, max_length=3, null=True),
        ),
    ]
