# Generated by Django 5.2.4 on 2025-07-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_search_category_product_search_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='package_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_product_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
