# Generated by Django 5.2.4 on 2025-11-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_free_shipping_product_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cta',
            field=models.CharField(blank=True, help_text="Compelling call-to-action text (e.g., '🕹 Relive the classics — get your RetroPlay™ Console now!')", max_length=200, verbose_name='Call to Action'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Enter product features, one per line. Will be displayed as bullet points.'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords for search engine optimization', max_length=500),
        ),
    ]
