# Generated by Django 5.2.4 on 2025-07-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_add_supplier_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='categories/'),
        ),
    ]
