# Generated by Django 5.2.4 on 2025-11-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_cta_product_features_product_seo_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cta',
            field=models.CharField(blank=True, help_text="Compelling call-to-action text (e.g., '🎮 Relive the classics – get your RetroPlay™ Console now!')", max_length=200, verbose_name='Call to Action'),
        ),
    ]
