# Generated by Django 5.2.4 on 2025-10-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0001_initial'),
        ('orders', '0003_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_type',
            field=models.CharField(blank=True, choices=[('TEMPORARY', 'Temporary Failure (Retryable)'), ('USER_CANCELLED', 'Cancelled by User'), ('PERMANENT', 'Permanent Failure'), ('TIMEOUT', 'Timeout')], max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='result_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='result_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal')], default='M-Pesa', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING'])), fields=('order', 'provider'), name='unique_order_provider'),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='ipn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipn.paypalipn'),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='paypalpayment',
            unique_together={('order',)},
        ),
    ]
