# Generated by Django 5.2.4 on 2025-10-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paypalpayment_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('FULFILLED', 'Fulfilled'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
