# Generated by Django 5.2.4 on 2025-10-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_order_delete_paypalpayment'),
    ]

    operations = [
    ]
