# Generated by Django 5.2.1 on 2025-07-14 21:53

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_refund_amount_payment_refund_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_last4',
            field=encrypted_model_fields.fields.EncryptedCharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='fraud_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('CREATED', 'Payment Created'), ('PROCESSING', 'Processing Started'), ('SUCCESS', 'Payment Succeeded'), ('FAILED', 'Payment Failed'), ('REFUND', 'Refund Processed'), ('WEBHOOK', 'Webhook Received')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payment.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'log_type'], name='payment_pay_created_109dcd_idx')],
            },
        ),
    ]
