# Generated by Django 5.2.4 on 2025-10-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_fields'),
    ]

    operations = [
        migrations.RemoveField(model_name='payment', name='old_amount'),
        migrations.RemoveField(model_name='payment', name='old_currency'),
        # ... remove old_original_amount, etc. ...
    ]
