# Generated by Django 5.2.1 on 2025-07-17 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_payment_alter_currencyrate_base_currency_and_more'),
        ('payment', '0006_payment_card_last4_payment_fraud_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_relation', to='orders.order'),
        ),
    ]
