# Generated by Django 5.2.4 on 2025-10-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_old_money_fields'),
    ]

    operations = [
        migrations.RemoveField(model_name='payment', name='old_original_amount'),
        migrations.RemoveField(model_name='payment', name='old_converted_amount'),
    ]
