# Generated by Django 5.2.4 on 2025-07-28 08:06

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_payment_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
