# Generated by Django 5.2.4 on 2025-10-29 06:22

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20251028_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], default='KES', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='converted_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='converted_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], default=None, editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], default=None, editable=False, max_length=3, null=True),
        ),
    ]
