# Generated by Django 5.2.4 on 2025-10-29 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_payment_amount_payment_amount_currency_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_order_provider',
        ),
    ]
