# Generated by Django 5.2.4 on 2025-11-09 20:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_shipping_cost_order_shipping_cost_currency_and_more'),
        ('payment', '0010_remove_payment_unique_order_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='processing_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failure_type',
            field=models.CharField(blank=True, choices=[('TEMPORARY', 'Temporary Failure (Retryable)'), ('USER_CANCELLED', 'Cancelled by User'), ('PERMANENT', 'Permanent Failure'), ('TIMEOUT', 'Timeout'), ('DUPLICATE', 'Duplicate Payment'), ('STOCK_ISSUE', 'Stock Validation Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal')], default='MPESA', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'provider'], name='payment_pay_status_f7259d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['checkout_request_id'], name='payment_pay_checkou_e2f706_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payment_pay_transac_f578fa_idx'),
        ),
    ]
