# Generated by Django 5.2.4 on 2025-11-09 20:20

from django.db import migrations
import uuid

def generate_unique_keys(apps, schema_editor):
    """Generate unique idempotency keys for existing payments"""
    Payment = apps.get_model('payment', 'Payment')
    # Only update rows that don't have a key
    for payment in Payment.objects.filter(idempotency_key__isnull=True):
        payment.idempotency_key = uuid.uuid4()
        payment.save(update_fields=['idempotency_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_idempotency_key_payment_locked_at_and_more'),

    ]

    operations = [
        migrations.RunPython(generate_unique_keys, migrations.RunPython.noop),
    ]