# Generated by Django 5.2.4 on 2025-11-09 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_populate_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
