# Generated by Django 5.2.4 on 2025-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_payment_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('PAYSTACK', 'Paystack')], default='MPESA', max_length=20),
        ),
    ]
