CATEGORIES = {
    "🎮 Game Controllers & Input Devices",
    "🖥️ Display & Visual Enhancements",
    "🕹️ Console Accessories",
    "🧩 PC Gaming Accessories",
    "🎧 Audio & Communication",
    "🪑 Furniture & Ergonomics",
    "🔌 Power & Charging",
    "🧳 Storage & Travel",
    "🧼 Maintenance & Protection",
    "📸 Streaming & Content Creation",
    "🎲 Retro & Niche Accessories",
    "🌐 Network & Online Gaming",
    "🧠 VR / AR Accessories",
    "📱 Mobile & Cloud Gaming",
    "💎 Merchandise & Collectibles",
    }