# Generated by Django 5.2.4 on 2025-10-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('FULFILLED', 'Fulfilled'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
