# Generated by Django 5.2.1 on 2025-07-17 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_currencyrate'),
        ('payment', '0006_payment_card_last4_payment_fraud_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_relation', to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='base_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling')], max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='target_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling')], max_length=3),
        ),
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['base_currency', 'target_currency'], name='orders_curr_base_cu_6efb08_idx'),
        ),
    ]
