# Generated by Django 5.2.1 on 2025-07-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_payment_alter_currencyrate_base_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_payment',
            new_name='payment',
        ),
    ]
