# Generated by Django 5.2.4 on 2025-10-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_update_country_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
