# Generated by Django 5.2.4 on 2025-10-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_payment'),
    ]

    operations = [
    ]
