# Generated by Django 5.2.4 on 2025-10-28 18:59

from django.db import migrations


class Migration(migrations.Migration):


    dependencies = [
        ('orders', '0009_rename_fields'),
    ]

    operations = [
        migrations.RemoveField(model_name='order', name='old_total'),
        migrations.RemoveField(model_name='order', name='old_currency'),
        migrations.RemoveField(model_name='orderitem', name='old_price'),
    ]