# Generated by Django 5.2.4 on 2025-10-29 06:22

import django.core.validators
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_old_money_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_product',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='min_order_item_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='dropship_order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='dropship_processed',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='estimated_delivery',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], default='KES', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], default='KES', editable=False, max_length=3),
        ),
    ]
