# Generated by Django 5.2.4 on 2025-10-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_delete_currencyrate_and_more'),
        ('store', '0010_product_discount_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product'),
        ),
    ]
