# Generated by Django 5.2.4 on 2025-11-02 16:12

import django.core.validators
import django_countries.fields
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AddField(
            model_name='order',
            name='billing_same_as_shipping',
            field=models.BooleanField(default=True, help_text='Use shipping address for billing'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.CharField(blank=True, help_text="Special delivery notes (e.g., 'Leave at door', 'Call on arrival')", max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(help_text='Street address or P.O. Box', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='KE', help_text='Shipping destination country', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='International format: +254712345678', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province/Region (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), help_text='Price per unit at time of purchase', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of units ordered', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
