# Generated by Django 5.2.4 on 2025-11-09 20:19

import django.core.validators
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), help_text='Total shipping cost for this order', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], default='KES', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='International format: +254712345678', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
    ]
